// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'train.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'train.g.dart';

@freezed
class Train with _$Train {
  const factory Train({
    @JsonKey(name: "DIRECTION") required String direction,
    @JsonKey(name: "TRAIN_ID") required String trainId,
    @JsonKey(name: "DESTINATION") required String destination,
    @JsonKey(name: "EVENT_TIME") required String eventTime,
    @JsonKey(name: "LINE") required String line,
    @JsonKey(name: "WAITING_TIME") required String waitingTime,
    @JsonKey(name: "WAITING_SECONDS") String? waitingSeconds,
    @JsonKey(name: "STATION") required String station,
    @JsonKey(name: "NEXT_ARR") String? nextArrival,
  }) = _Train;

  factory Train.fromJson(Map<String, Object?> json) => _$TrainFromJson(json);
}
